name: Lint

on:
  push:
    paths-ignore:
      - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
      - 'CHANGELOG.md'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - parallel:
        - name: golangci-lint
          uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9
          with:
            version: v2.12.2
  
        - name: Run zizmor
          uses: zizmorcore/zizmor-action@6fc4b006235f201fdab3722e17240ab420d580e5 # v0.6.1
          with:
            persona: pedantic
            advanced-security: 'false'
            annotations: 'true'
            version: '1.27.0'
            # TODO: add enable strict collection when the action enables it
