name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

permissions: {}

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      attestations: write
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5

      - name: Checkout
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Build and upload binaries
        if: ${{ steps.release.outputs.release_created }}
        uses: cli/gh-extension-precompile@76961aa3bd1123d0a6fd42d0a41aca0696937c39 # v2.2.0
        with:
          generate_attestations: true
          go_version_file: go.mod
          release_tag: ${{ steps.release.outputs.tag_name }}
